=== pmmp/BedrockBlockUpgradeSchema/nbt_upgrade_schema_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$defs": {
		"blockStateProperty": {
			"type": "object",
			"minProperties": 1,
			"maxProperties": 1,
			"additionalProperties": false,
			"properties": {
				"int": {
					"type": "integer"
				},
				"string": {
					"type": "string"
				},
				"byte": {
					"type": "integer"
				}
			}
		}
	},
	"type": "object",
	"additionalProperties": false,
	"required": [
		"maxVersionMajor",
		"maxVersionMinor",
		"maxVersionPatch",
		"maxVersionRevision"
	],
	"properties": {
		"maxVersionMajor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionMinor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionPatch": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionRevision": {
			"type": "integer",
			"minimum": 0
		},
		"renamedIds": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"renamedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"addedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"$ref": "#/$defs/blockStateProperty"
				}
			}
		},
		"removedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValues": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValuesIndex": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"old": {
							"$ref": "#/$defs/blockStateProperty"
						},
						"new": {
							"$ref": "#/$defs/blockStateProperty"
						}
					},
					"additionalProperties": false
				}
			}
		},
		"remappedStates": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"required": [
						"oldState",
						"newState"
					],
					"oneOf": [
						{
							"required": ["newName"]
						},
						{
							"required": ["newFlattenedName"]
						}
					],
					"properties": {
						"oldState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"newName": {
							"type": "string"
						},
						"newFlattenedName": {
							"type": "object",
							"required": [
								"prefix",
								"flattenedProperty",
								"suffix"
							],
							"properties": {
								"prefix": {
									"type": "string"
								},
								"flattenedProperty": {
									"type": "string"
								},
								"flattenedPropertyType": {
									"type": "string",
									"enum": ["int", "string", "byte"]
								},
								"suffix": {
									"type": "string"
								},
								"flattenedValueRemaps": {
									"type": "object",
									"additionalProperties": {
										"type": "string"
									}
								}
							},
							"additionalProperties": false
						},
						"newState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"copiedState": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					},
					"additionalProperties": false
				}
			}
		}
	}
}

=== pmmp/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0281_1.20.80.24_beta_to_1.21.0.25_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 21,
    "maxVersionPatch": 0,
    "maxVersionRevision": 3,
    "addedProperties": {
        "minecraft:trial_spawner": {
            "ominous": {
                "byte": 0
            }
        },
        "minecraft:vault": {
            "ominous": {
                "byte": 0
            }
        }
    },
    "remappedStates": {
        "minecraft:coral_block": [
            {
                "oldState": {
                    "dead_bit": {
                        "byte": 0
                    }
                },
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "coral_color",
                    "suffix": "_coral_block",
                    "flattenedValueRemaps": {
                        "blue": "tube",
                        "pink": "brain",
                        "purple": "bubble",
                        "red": "fire",
                        "yellow": "horn"
                    }
                },
                "newState": null
            },
            {
                "oldState": {
                    "dead_bit": {
                        "byte": 1
                    }
                },
                "newFlattenedName": {
                    "prefix": "minecraft:dead_",
                    "flattenedProperty": "coral_color",
                    "suffix": "_coral_block",
                    "flattenedValueRemaps": {
                        "blue": "tube",
                        "pink": "brain",
                        "purple": "bubble",
                        "red": "fire",
                        "yellow": "horn"
                    }
                },
                "newState": null
            }
        ],
        "minecraft:double_plant": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "double_plant_type",
                    "suffix": "",
                    "flattenedValueRemaps": {
                        "fern": "large_fern",
                        "grass": "tall_grass",
                        "paeonia": "peony",
                        "rose": "rose_bush",
                        "syringa": "lilac"
                    }
                },
                "newState": null,
                "copiedState": [
                    "upper_block_bit"
                ]
            }
        ],
        "minecraft:stone_block_slab": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "stone_slab_type",
                    "suffix": "_slab",
                    "flattenedValueRemaps": {
                        "wood": "petrified_oak"
                    }
                },
                "newState": null,
                "copiedState": [
                    "minecraft:vertical_half"
                ]
            }
        ],
        "minecraft:tallgrass": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "tall_grass_type",
                    "suffix": "",
                    "flattenedValueRemaps": {
                        "default": "short_grass",
                        "snow": "fern",
                        "tall": "short_grass"
                    }
                },
                "newState": null
            }
        ]
    }
}

=== pmmp/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0301_1.21.20.24_beta_to_1.21.30.24_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 21,
    "maxVersionPatch": 30,
    "maxVersionRevision": 7,
    "removedProperties": {
        "minecraft:structure_void": [
            "structure_void_type"
        ]
    },
    "remappedStates": {
        "minecraft:chemistry_table": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "chemistry_table_type",
                    "suffix": ""
                },
                "newState": null,
                "copiedState": [
                    "direction"
                ]
            }
        ],
        "minecraft:cobblestone_wall": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "wall_block_type",
                    "suffix": "_wall",
                    "flattenedValueRemaps": {
                        "end_brick": "end_stone_brick"
                    }
                },
                "newState": null,
                "copiedState": [
                    "wall_connection_type_east",
                    "wall_connection_type_north",
                    "wall_connection_type_south",
                    "wall_connection_type_west",
                    "wall_post_bit"
                ]
            }
        ],
        "minecraft:colored_torch_bp": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:colored_torch_",
                    "flattenedProperty": "color_bit",
                    "flattenedPropertyType": "byte",
                    "suffix": "",
                    "flattenedValueRemaps": {
                        "0": "blue",
                        "1": "purple",
                        "dummy": "map_not_list"
                    }
                },
                "newState": null,
                "copiedState": [
                    "torch_facing_direction"
                ]
            }
        ],
        "minecraft:colored_torch_rg": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:colored_torch_",
                    "flattenedProperty": "color_bit",
                    "flattenedPropertyType": "byte",
                    "suffix": "",
                    "flattenedValueRemaps": {
                        "0": "red",
                        "1": "green",
                        "dummy": "map_not_list"
                    }
                },
                "newState": null,
                "copiedState": [
                    "torch_facing_direction"
                ]
            }
        ],
        "minecraft:purpur_block": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "chisel_type",
                    "suffix": "",
                    "flattenedValueRemaps": {
                        "chiseled": "deprecated_purpur_block_1",
                        "default": "purpur_block",
                        "lines": "purpur_pillar",
                        "smooth": "deprecated_purpur_block_2"
                    }
                },
                "newState": null,
                "copiedState": [
                    "pillar_axis"
                ]
            }
        ],
        "minecraft:sponge": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "sponge_type",
                    "suffix": "sponge",
                    "flattenedValueRemaps": {
                        "dry": "",
                        "wet": "wet_"
                    }
                },
                "newState": null
            }
        ],
        "minecraft:tnt": [
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "allow_underwater_bit",
                    "flattenedPropertyType": "byte",
                    "suffix": "tnt",
                    "flattenedValueRemaps": {
                        "0": "",
                        "1": "underwater_",
                        "dummy": "map_not_list"
                    }
                },
                "newState": null,
                "copiedState": [
                    "explode_bit"
                ]
            }
        ]
    }
}
